version: "1.0"
stages:
  - "prepare"
  - "dcr"

steps:
  sbat_main_clone:
    type: git-clone
    title: Git Clone SecureBankingAccessToolkit/conformance-dcr
    repo: SecureBankingAccessToolkit/conformance-dcr
    revision: "sbat-master"
    stage: prepare
    git: github-bot
  prepare_environment_context:
    title: "Preparing environment"
    image: eu.gcr.io/sbat-gcr-develop/ci/gcloud-tools:latest
    stage: prepare
    commands:
      - |
        set -e      
        config_json_template=$(cat conformance-dcr/sbat-create-dcr-config.json.jq.template)
        
        # --arg are treated as strings and get escaped and quoted
        # --jsonargs are treated as valid json, we use this to supply the certs as they contain \n chars which we do not want escaping
        jq -n \
           --arg wellknown_endpoint "${WELLKNOWN_ENDPOINT}" \
           --arg ssa "${FAPI_1_SSA}" \
           --arg issuer "${FAPI_1_ISSUER}" \
           --argjson signing_private_key "\"${FAPI_1_OB_SEAL_KEY}\"" \
           --argjson transport_cert "\"${FAPI_1_OB_WAC_CERT}\"" \
           --argjson transport_private_key "\"${FAPI_1_OB_WAC_KEY}\"" \
           --arg token_endpoint_auth_method "${TOKEN_ENDPOINT_AUTH_METHOD}" \
           "${config_json_template}" > fapi-1-dcr-config.json
        
        jq -n \
           --arg wellknown_endpoint "${WELLKNOWN_ENDPOINT}" \
           --arg ssa "${FAPI_2_SSA}" \
           --arg issuer "${FAPI_2_ISSUER}" \
           --argjson signing_private_key "\"${FAPI_2_OB_SEAL_KEY}\"" \
           --argjson transport_cert "\"${FAPI_2_OB_WAC_CERT}\"" \
           --argjson transport_private_key "\"${FAPI_2_OB_WAC_KEY}\"" \
           --arg token_endpoint_auth_method "${TOKEN_ENDPOINT_AUTH_METHOD}" \
           "${config_json_template}" > fapi-2-dcr-config.json
        

  create_dcr:
    title: "Creating DCRs"
    image: eu.gcr.io/sbat-gcr-develop/securebanking/conformance-dcr:v1.3.0
    stage: dcr
    volumes:
      - ./fapi-1-dcr-config.json:/fapi-1-dcr-config.json # host path is relative to /codefresh/volume
      - ./fapi-2-dcr-config.json:/fapi-2-dcr-config.json
    commands:
      - |
        dcr -config-path /fapi-1-dcr-config.json --debug > fapi-1.log
        dcr -config-path /fapi-2-dcr-config.json --debug > fapi-2.log

        # extract the client_id that was created, the logs contain a line with the registration response json obj
        fapi_1_client_id=$(cat fapi-1.log | grep "register res:" | grep -o "{.*}" | jq --raw-output .client_id)
        echo "fapi-compliance-1 client_id: ${fapi_1_client_id}"

        fapi_2_client_id=$(cat fapi-2.log | grep "register res:" | grep -o "{.*}" | jq --raw-output .client_id)
        echo "fapi-compliance-2 client_id: ${fapi_2_client_id}"