name: build_and_push
run-name: Build and push image
on:
  push:
    branches:
      - sbat-master
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: conformance-dcr
  GITHUB_REF: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DEV_GAR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Auth Docker
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
      
      - name: Build & Push Docker Image
        run: |
          docker build --file Dockerfile-sbat -t ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:${{ env.GITHUB_REF }} -t ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest .
          docker push ${{ vars.GAR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }} --all-tags