name: build_and_test
run-name: Build and Test Image
on:
  pull_request:
    branches:
      - sbat-master
    paths-ignore:
      - README.md

env:
  PR_NUMBER: pr-${{ github.event.number }}
  SERVICE_NAME: uk-conformance-dcr

jobs:
  check:
    runs-on: ubuntu-latest
    container: golang:1.17-alpine3.15
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    name: Check New Changes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: apk update && apk add git make bash curl
      - name: make tools
        run: make tools
      - name: Build
        run: make build
      - name: Test
        run: make test
  build:
    runs-on: ubuntu-latest
    name: Build Image
    needs: check
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Auth Docker
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev
      
      - name: Build & Push Docker Image
        run: |
          docker build --file Dockerfile-sbat -t ${{ vars.GAR_DEV_REPO }}/securebanking/pr/${{ env.SERVICE_NAME }}:${{ env.PR_NUMBER }} .
          docker push ${{ vars.GAR_DEV_REPO }}/securebanking/pr/${{ env.SERVICE_NAME }}:${{ env.PR_NUMBER }}
  test:
    runs-on: ubuntu-latest
    name: Test Image
    needs: build
    steps:  
      - name: 'Run Conformance-DCR Tests'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v IMAGE_REPO=securebanking/pr/${{ env.SERVICE_NAME }} -v TAG=${{ env.PR_NUMBER }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/dev-dcr-conformance-tests'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: 'github-actions-trigger-dcr'
        id: run-tests