name: build_and_push
run-name: Build and push image
on:
  push:
    branches:
      - sbat-master
    paths-ignore:
      - README.md

env:
  SERVICE_NAME: conformance-dcr
  GITHUB_REF: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auth GCloud GCR
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build & Push Docker Image
        run: |
          docker build --file Dockerfile-sbat -t eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:${{ env.GITHUB_REF }} .
          docker tag eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:${{ env.GITHUB_REF }} eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}:latest
          docker push --all-tags eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/${{ env.SERVICE_NAME }}