name: Merge - Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - sbat-master
      - ob-v*
    paths-ignore:
      - '**/README.md'

jobs:
  run_merge-template:
    name: Merge - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/reusable-merge.yml@main
    secrets: inherit
    with:
      componentBranch: ${{ github.head_ref || github.ref_name }}
      componentName: conformance-dcr
      dockerTag: $(echo ${{ github.sha }} | cut -c1-7)
