name: Check Changes
on:
  pull_request:
    branches:
      - sbat-master
    paths-ignore:
      - '**/README.md'
jobs:
  run_pr-template:
    name: PR - Build and Deploy
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/conformance-dcr/build-and-deploy.yml@1389-standard-steps-for-workflows
    secrets: inherit
    with:
      componentName: conformance-dcr
      prNumber: pr-${{ github.event.number }}