name: Check Changes
on:
  push:
    branches-ignore:
      - 'sbat-master'
    paths-ignore:
      - '**/README.md'
jobs:
  run_pr-template:
    name: Build Changes
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/dcr-build-on-push.yml@1389-standard-steps-for-workflows
    secrets: inherit
    with:
      componentName: conformance-dcr