name: Rebase
on:
  workflow_dispatch:
  push:
    branches:
      - sbat-master
jobs:
  run_rebase-template:
    name: Rebase
    uses: SecureApiGateway/secure-api-gateway-ci/.github/workflows/merge-branch.yml@main
    secrets: inherit
    with:
      componentName: conformance-dcr
      sourceBranch: sbat-master
      targetBranch: ob-v4